apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.env.PORT }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: MONGO_URI
              value: "{{ .Values.env.MONGO_URI }}"
            - name: REDIS_URL
              value: "{{ .Values.env.REDIS_URL }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
            - name: BASE_URL
              value: "{{ .Values.env.BASE_URL }}"
